# Generated by Django 5.1.15 on 2026-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=16)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('verification_mode', models.CharField(blank=True, max_length=64)),
                ('event_code', models.CharField(blank=True, max_length=64)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_attendancerecord',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee_id', 'timestamp'], name='core_attend_employe_4f819b_idx'), models.Index(fields=['-created_at'], name='core_attend_created_be3ee1_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee_id', 'timestamp', 'event_type'), name='unique_emp_ts_event')],
            },
        ),
    ]
