# Generated by Django 5.1.15 on 2026-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_emp_ts_event',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='core_attend_created_be3ee1_idx',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='event_code',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='verification_mode',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.CharField(choices=[('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='branch',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['branch', 'timestamp'], name='core_attend_branch_9f7648_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee_id', 'timestamp', 'attendance_status', 'branch'), name='unique_emp_ts_status_branch'),
        ),
    ]
