# Generated by Django 5.1.15 on 2026-02-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_branch',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='core_attend_branch__9eac15_idx',
            old_name='core_attend_branch_9f7648_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='core_userpr_branch__c5e3ce_idx',
            old_name='core_userpr_branch_9c0988_idx',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.branch'),
        ),
    ]
