# Generated by Django 5.1.15 on 2026-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('COS', 'Contract of Service (COS)'), ('JO', 'Job Order (JO)')], db_index=True, default='COS', max_length=3),
        ),
    ]
