# Generated by Django 5.1.15 on 2026-02-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('COS', 'Contract of Service'), ('JO', 'Job Order')], db_index=True, max_length=3),
        ),
    ]
