# Generated by Django 5.1.15 on 2026-02-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leaverequest_leaveattachment'),
        ('core', '0007_userprofile_core_userpr_departm_aa80d8_idx_and_more'),
    ]

    operations = [
    ]
