# Generated by Django 5.1.15 on 2026-02-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260207_2357'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_departm_aa80d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_employm_b24a16_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employment_type',
        ),
    ]
