# Generated by Django 5.1.15 on 2026-02-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_core_userpr_departm_aa80d8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_amount', models.DecimalField(decimal_places=2, default=760, max_digits=10)),
                ('pagibig_amount', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('philhealth_mode', models.CharField(default='percent', max_length=10)),
                ('philhealth_value', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
            options={
                'db_table': 'core_employeecontribution',
            },
        ),
        migrations.CreateModel(
            name='HolidaySuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('holiday', 'Regular Holiday'), ('suspension', 'Work Suspension'), ('special', 'Special Non-Working Day')], default='holiday', max_length=20)),
                ('scope', models.CharField(choices=[('nationwide', 'Nationwide'), ('region', 'MIMAROPA Region'), ('branch', 'Specific Branch')], default='region', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_holidaysuspension',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('totals_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('totals_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_payrollbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('premium_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('absences', models.PositiveIntegerField(default=0)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gov_contributions_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issues', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_payrollitem',
                'ordering': ['profile__user__username'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('pay_mode', models.CharField(choices=[('MONTHLY', 'Monthly'), ('FIRST_HALF', 'Kinsenas (1st Half)'), ('SECOND_HALF', 'Katapusan (2nd Half)')], default='MONTHLY', max_length=20)),
            ],
            options={
                'db_table': 'core_payrollperiod',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('premium_rate_percent', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('philhealth_default_mode', models.CharField(default='percent', max_length=10)),
                ('philhealth_default_value', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('undertime_penalty_per_minute', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('grace_minutes_normal', models.PositiveIntegerField(default=15)),
                ('flag_ceremony_cutoff_time', models.TimeField(default='08:00')),
                ('lunch_break_required', models.BooleanField(default=False)),
                ('daily_hours_required', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('work_start_time', models.TimeField(default='08:00')),
                ('work_end_time', models.TimeField(default='17:00')),
            ],
            options={
                'db_table': 'core_payrollrule',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('COS', 'Contract of Service (COS)'), ('JO', 'Job Order (JO)')], db_index=True, default='COS', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['branch', 'employment_type'], name='core_userpr_branch__d71a9c_idx'),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrib', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='holidaysuspension',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.branch'),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_batches', to='core.branch'),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.payrollbatch'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_batches', to='core.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rules', to='core.branch'),
        ),
        migrations.AddIndex(
            model_name='holidaysuspension',
            index=models.Index(fields=['date', 'scope'], name='core_holida_date_433f56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatch',
            unique_together={('branch', 'period')},
        ),
    ]
