# Generated by Django 5.1.15 on 2026-02-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employeecontribution_holidaysuspension_payrollbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='manual_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
