# Generated by Django 5.1.15 on 2026-04-06 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_biometricdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='biometricdevice',
            table='core_biometricdevice',
        ),
        migrations.CreateModel(
            name='EmployeeDayRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('remark_type', models.CharField(choices=[('holiday', 'Holiday'), ('suspension', 'Work Suspension'), ('special', 'Special Non-Working Day')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_day_remarks', to='core.branch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_remarks', to='core.holidaysuspension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_employeedayremark',
                'ordering': ['-date', 'user__username'],
                'indexes': [models.Index(fields=['branch', 'date'], name='core_employ_branch__32f76a_idx'), models.Index(fields=['user', 'date'], name='core_employ_user_id_0d8a4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'remark_type'), name='unique_user_date_remark_type')],
            },
        ),
    ]
