# Generated by Django 5.1.15 on 2026-04-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_biometricdevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={},
        ),
        migrations.AlterModelTable(
            name='biometricdevice',
            table=None,
        ),
        migrations.DeleteModel(
            name='EmployeeDayRemark',
        ),
    ]
