# Generated by Django 5.1.15 on 2026-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_travelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biometric_employee_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Employee ID used by the Hikvision biometric device.', max_length=64),
        ),
    ]
