# Generated by Django 5.1.15 on 2026-05-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_biometric_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrule',
            name='late_penalty_per_minute',
        ),
        migrations.RemoveField(
            model_name='payrollrule',
            name='undertime_penalty_per_minute',
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='ot_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='pagibig_min',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='salary_divisor',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='sss_min',
            field=models.DecimalField(decimal_places=2, default=760, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='pay_mode',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('FIRST_HALF', 'Semi-monthly 1st Half'), ('SECOND_HALF', 'Semi-monthly 2nd Half')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrule',
            name='lunch_break_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'core_overtimerequest',
            },
        ),
    ]
