# Generated by Django 5.1.15 on 2026-05-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_payrollrule_late_penalty_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='payrollrule',
            old_name='pagibig_min',
            new_name='pagibig_minimum',
        ),
        migrations.RenameField(
            model_name='payrollrule',
            old_name='sss_min',
            new_name='sss_minimum',
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payrollrule',
            name='salary_divisor',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerequest',
            unique_together={('profile', 'date')},
        ),
    ]
