# Generated by Django 5.1.15 on 2026-07-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_overtimerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollbatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='gsis_employee_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GSIS employee share deducted from permanent employee pay.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='gsis_employer_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GSIS employer share for records/costing only. Not deducted from employee pay.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='loan_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total loan deductions such as calamity loan or multi-purpose loan.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='other_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other authorized deductions.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='other_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other employer contribution for records/costing only. Not deducted from employee pay.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeecontribution',
            name='wtax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax amount for permanent employees.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='employee_type_scope',
            field=models.CharField(choices=[('ALL', 'All Employee Types'), ('JO', 'Job Order Only'), ('COS', 'Contract of Service Only'), ('PERMANENT', 'Permanent Only')], db_index=True, default='ALL', help_text='Scope of employees included in this payroll batch.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_earnings_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other regular earnings/allowances if approved by client policy.', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pera_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PERA or standard allowance for permanent employees.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeecontribution',
            name='philhealth_mode',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('COS', 'Contract of Service (COS)'), ('JO', 'Job Order (JO)'), ('PERMANENT', 'Permanent')], db_index=True, default='COS', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatch',
            unique_together={('branch', 'period', 'employee_type_scope')},
        ),
    ]
