# Generated by Django 5.1.15 on 2026-07-09 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_payrollbatch_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedDTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.JSONField(blank=True, default=list, help_text='Locked DTR rows snapshot.')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Locked DTR summary snapshot.')),
                ('source_meta', models.JSONField(blank=True, default=dict, help_text='Extra source information such as batch ID, processor, and scope.')),
                ('is_locked', models.BooleanField(db_index=True, default=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_dtrs', to='core.branch')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_dtrs', to=settings.AUTH_USER_MODEL)),
                ('payroll_item', models.ForeignKey(blank=True, help_text='PayrollItem used as source when this DTR was finalized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_dtrs', to='core.payrollitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_dtrs', to='core.payrollperiod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_dtrs', to='core.userprofile')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_dtrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_finalizeddtr',
                'ordering': ['-finalized_at', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'period'], name='core_finali_branch__347aab_idx'), models.Index(fields=['profile', 'period', 'is_locked'], name='core_finali_profile_d45b8b_idx')],
                'unique_together': {('profile', 'period')},
            },
        ),
    ]
