# Generated by Django 5.1.15 on 2026-07-16 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_finalizeddtr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollbatch',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
