# Generated by Django 5.1.15 on 2026-08-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_payroll_accuracy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrule',
            name='earliest_creditable_time',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='lunch_end_time',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='payrollrule',
            name='lunch_start_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
