# Generated by Django 5.1.15 on 2026-10-03 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_payrollrule_earliest_creditable_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Branch Hikvision Connector', max_length=150)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_connector', to='core.branch')),
            ],
            options={
                'db_table': 'core_branchconnector',
                'ordering': ['branch__name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSyncRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_sync_requests', to='core.branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_requests', to='core.biometricdevice')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_biometric_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_biometricsyncrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='bio_sync_branch_status_idx'), models.Index(fields=['device', 'status'], name='bio_sync_device_status_idx')],
            },
        ),
    ]
